#!/usr/bin/env node
/**
 * Dependency graph for the app source.
 *
 * Answers "what breaks if I change this?" without a single grep. lib/store.ts and
 * lib/prompts.ts are imported almost everywhere in this repo and there is no other
 * way to see that.
 *
 *   node scripts/dep-graph.mjs           write docs/dep-graph.md
 *   node scripts/dep-graph.mjs --stdout  print instead of writing
 *   node scripts/dep-graph.mjs --who lib/store.ts   who imports one file
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { ROOT, moduleGraph, findCycles, isMain } from "./lib/scan.mjs";

const OUT = "docs/dep-graph.md";

/** Mermaid node ids must be alphanumeric. */
const id = (file) => file.replace(/[^A-Za-z0-9]/g, "_");

/** Which subgraph a file belongs to, and its display label. */
function group(file) {
  if (file.startsWith("app/api/")) return "API routes";
  if (file.startsWith("app/")) return "Pages";
  if (file.startsWith("components/")) return "Components";
  if (file.startsWith("lib/")) return "Lib";
  if (file.startsWith("agent/")) return "Agent (local)";
  if (file.startsWith("scripts/")) return "Scripts";
  return "Root";
}

const GROUP_ORDER = ["Pages", "API routes", "Components", "Lib", "Root", "Agent (local)", "Scripts"];

/**
 * The scripts/ tooling and the standalone agent/ runner are their own worlds and
 * only add noise to a graph about the app. Keep them out of the diagram, but
 * still list them in the reverse index below it.
 */
const inDiagram = (file) => !file.startsWith("scripts/") && !file.startsWith("agent/");

function mermaid(modules) {
  const files = [...modules.keys()].filter(inDiagram);
  const byGroup = new Map(GROUP_ORDER.map((g) => [g, []]));
  for (const f of files) byGroup.get(group(f))?.push(f);

  const lines = ["```mermaid", "graph LR"];
  for (const g of GROUP_ORDER) {
    const members = byGroup.get(g) ?? [];
    if (!members.length) continue;
    lines.push(`  subgraph ${JSON.stringify(g)}`);
    for (const f of members) lines.push(`    ${id(f)}["${f}"]`);
    lines.push("  end");
  }
  for (const f of files) {
    for (const dep of modules.get(f).imports) {
      if (inDiagram(dep)) lines.push(`  ${id(f)} --> ${id(dep)}`);
    }
  }
  lines.push("```");
  return lines.join("\n");
}

function report() {
  const { modules, importedBy } = moduleGraph();
  const cycles = findCycles(modules);

  const ranked = [...importedBy.entries()]
    .filter(([f]) => inDiagram(f))
    .sort((a, b) => b[1].length - a[1].length);

  const hubs = ranked.filter(([, users]) => users.length >= 3);

  // An entry point is reached by the framework or a CLI, not by an import: pages,
  // routes, middleware, root config, and anything under scripts/ or agent/.
  const isEntry = (f) =>
    /^app\/.*(page|route|layout|error)\.tsx?$/.test(f) ||
    /^[^/]+\.config\.(mjs|js|ts)$/.test(f) ||
    f === "middleware.ts" ||
    f.startsWith("scripts/") ||
    f.startsWith("agent/") ||
    f.endsWith(".d.ts");

  const orphans = [...importedBy.entries()]
    .filter(([f, users]) => users.length === 0 && !isEntry(f))
    .map(([f]) => f);

  const out = [];
  out.push("# Dependency graph");
  out.push("");
  out.push(`_Generated by \`node scripts/dep-graph.mjs\` — ${new Date().toISOString().slice(0, 10)}._`);
  out.push("");
  out.push(`${modules.size} source modules. \`scripts/\` and \`agent/\` are excluded from the diagram (standalone tooling) but included in the index below.`);
  out.push("");
  out.push(mermaid(modules));
  out.push("");

  out.push("## Blast radius — most-imported modules");
  out.push("");
  out.push("Change one of these and every file listed has to keep working.");
  out.push("");
  out.push("| Module | Importers | Imported by |");
  out.push("| --- | --- | --- |");
  for (const [file, users] of hubs) {
    out.push(`| \`${file}\` | ${users.length} | ${users.map((u) => `\`${u}\``).join(", ")} |`);
  }
  out.push("");

  out.push("## Reverse index — who imports what");
  out.push("");
  out.push("<details><summary>Every module with at least one importer</summary>");
  out.push("");
  for (const [file, users] of ranked) {
    if (!users.length) continue;
    out.push(`- \`${file}\` ← ${users.map((u) => `\`${u}\``).join(", ")}`);
  }
  out.push("");
  out.push("</details>");
  out.push("");

  out.push("## Warnings");
  out.push("");
  if (cycles.length) {
    out.push("**Import cycles:**");
    for (const c of cycles) out.push(`- ${c.map((f) => `\`${f}\``).join(" → ")}`);
  } else {
    out.push("- No import cycles.");
  }
  if (orphans.length) {
    out.push(`- Unreferenced (nothing imports them, and they are not entry points): ${orphans.map((f) => `\`${f}\``).join(", ")}`);
  } else {
    out.push("- No unreferenced modules.");
  }
  out.push("");

  return { text: out.join("\n"), cycles, orphans, modules, importedBy };
}

if (isMain(import.meta.url)) {
  const whoIdx = process.argv.indexOf("--who");
  if (whoIdx !== -1) {
    const target = process.argv[whoIdx + 1];
    const { importedBy } = moduleGraph();
    const users = importedBy.get(target);
    if (!users) {
      console.error(`Not a tracked source file: ${target}`);
      process.exit(1);
    }
    console.log(users.length ? users.join("\n") : "(nothing imports it)");
  } else {
    const { text, cycles, orphans, modules } = report();
    if (process.argv.includes("--stdout")) {
      console.log(text);
    } else {
      writeFileSync(join(ROOT, OUT), text + "\n", "utf8");
      console.log(`${OUT} · ${modules.size} modules · ${cycles.length} cycles · ${orphans.length} unreferenced`);
    }
  }
}

export { report };
